//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pinjam
    {
        public string NoPinjam { get; set; }
        public string IdUser { get; set; }
        public string IdBuku { get; set; }
        public System.DateTime TglPinjam { get; set; }
        public System.DateTime TglKembali { get; set; }
        public int TotalHari { get; set; }
        public decimal TotalSewa { get; set; }
    
        public virtual Buku Buku { get; set; }
        public virtual User User { get; set; }
    }
}
